# Generated by tools/brew-formula.sh. Do not edit by hand.
class Kalku < Formula
  desc "Mutation testing for humans, CI, and coding agents"
  homepage "https://github.com/lnds/kalku"
  version "0.6.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/lnds/kalku/releases/download/v0.6.1/kalku-v0.6.1-darwin-arm64.tar.gz"
      sha256 "a77a081c790a1fb741e3fafdcd03affe84f77c5e87851e5d49c47c0168e815c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lnds/kalku/releases/download/v0.6.1/kalku-v0.6.1-linux-x86_64.tar.gz"
      sha256 "c029546112bb9e3b3f631dc87c5315a1a781f585bb9ccd9daaed2c9a508c57ab"
    end
  end

  def install
    bin.install "kalku", "kalku-kaikai", "kalku-rust", "kalku-python"
  end

  test do
    assert_match "outcomes", shell_output("#{bin}/kalku info")
  end
end
