# Generated by tools/brew-formula.sh. Do not edit by hand.
class Kalku < Formula
  desc "Mutation testing for humans, CI, and coding agents"
  homepage "https://github.com/lnds/kalku"
  version "0.11.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/lnds/kalku/releases/download/v0.11.0/kalku-v0.11.0-darwin-arm64.tar.gz"
      sha256 "fa573243c8af879f30913d6d7bd96d34f032c9e5060656390d48b7e1105f691b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lnds/kalku/releases/download/v0.11.0/kalku-v0.11.0-linux-x86_64.tar.gz"
      sha256 "3335f358044ad0c9ff8b5c569b7a9f455f3bbb609b562d2fe249e891d6a22910"
    end
  end

  def install
    bin.install "kalku", "kalku-kaikai", "kalku-rust", "kalku-python", "kalku-java"
  end

  test do
    assert_match "outcomes", shell_output("#{bin}/kalku info")
  end
end
